# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfazQT.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 781, 73))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.topMenu = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.topMenu.setContentsMargins(0, 0, 0, 0)
        self.topMenu.setObjectName("topMenu")
        self.botonLeer = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.botonLeer.setObjectName("botonLeer")
        self.topMenu.addWidget(self.botonLeer)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.topMenu.addItem(spacerItem)
        self.botonEscribir = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.botonEscribir.setObjectName("botonEscribir")
        self.topMenu.addWidget(self.botonEscribir)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.topMenu.addItem(spacerItem1)
        self.textoRutaDelArchivo = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.textoRutaDelArchivo.setObjectName("textoRutaDelArchivo")
        self.topMenu.addWidget(self.textoRutaDelArchivo)
        self.buscarDirectorio = QtWidgets.QToolButton(self.horizontalLayoutWidget)
        self.buscarDirectorio.setObjectName("buscarDirectorio")
        self.topMenu.addWidget(self.buscarDirectorio)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 120, 781, 441))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textoArchivoModificable = QtWidgets.QPlainTextEdit(self.horizontalLayoutWidget_2)
        self.textoArchivoModificable.setReadOnly(False)
        self.textoArchivoModificable.setBackgroundVisible(False)
        self.textoArchivoModificable.setPlaceholderText("")
        self.textoArchivoModificable.setObjectName("textoArchivoModificable")
        self.horizontalLayout.addWidget(self.textoArchivoModificable)
        self.textoArchivo = QtWidgets.QPlainTextEdit(self.horizontalLayoutWidget_2)
        self.textoArchivo.setUndoRedoEnabled(False)
        self.textoArchivo.setReadOnly(True)
        self.textoArchivo.setBackgroundVisible(False)
        self.textoArchivo.setPlaceholderText("")
        self.textoArchivo.setObjectName("textoArchivo")
        self.horizontalLayout.addWidget(self.textoArchivo)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(9, 91, 781, 25))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.botonRestablecer = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.botonRestablecer.sizePolicy().hasHeightForWidth())
        self.botonRestablecer.setSizePolicy(sizePolicy)
        self.botonRestablecer.setObjectName("botonRestablecer")
        self.horizontalLayout_5.addWidget(self.botonRestablecer)
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.buscarDirectorio.clicked.connect(MainWindow.searchFolderClicked)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.botonLeer.setText(_translate("MainWindow", "Leer"))
        self.botonEscribir.setText(_translate("MainWindow", "Modificar"))
        self.buscarDirectorio.setText(_translate("MainWindow", "..."))
        self.label_2.setText(_translate("MainWindow", "Modificar"))
        self.botonRestablecer.setText(_translate("MainWindow", "<----"))
        self.label.setText(_translate("MainWindow", "Solo lectura"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

